"""add language to posts

Revision ID: 787019f21f0d
Revises: 662a059643cf
Create Date: 2019-01-03 13:58:32.546049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787019f21f0d'
down_revision = '662a059643cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
